server:
  port: 48001
  servlet:
    context-path: /seller_lx
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.101:3306/sell?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

logging:
  config: classpath:logback-seller_lx.xml
wechat:
  mpAppId: wxb49165de84009517
  mpAppSecret: b7f660477e30f855a8aa9c210aac0773
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://lktalented.natapp1.cc/seller_lx/pay/notify


projectUrl:
  wechatMpAuthorize: http://lktalented.natapp1.cc
#  pattern:
#    console: "%d - %msg%n"
##  file: E:\springboot-imooc-logs\sell.log
#  level:
#    com.xhh.sell_lx: info
