server:
  port: 48001
  servlet:
    context-path: /seller_lx
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.130:3306/sell?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

logging:
  config: classpath:logback-seller_lx.xml
#  pattern:
#    console: "%d - %msg%n"
##  file: E:\springboot-imooc-logs\sell.log
#  level:
#    com.xhh.sell_lx: info
